version: "3.1"

services:
  galeria:
    container_name: galeria
    image: yammy08/galeria:latest
    ports:
      - 80:5000
    restart: always
<<<<<<< HEAD
=======
    
>>>>>>> 4d77072e8022dec23b521a0baece43d8558121d5
